---
# Run the perf tool on the mountpoint
- name: Run delete tests
  command:
  args:
    argv:
      - /usr/src/smallfile/smallfile_cli.py
      - --stonewall
      - N
      - --operation
      - "{{ item }}"
      - --threads
      - "{{ glusterfs_perf_smallfile_threads }}"
      - --file-size
      - "{{ glusterfs_perf_smallfile_file_size }}"
      - --files
      - "{{ glusterfs_perf_smallfile_num_of_files }}"
      - --top
      - "{{ glusterfs_perf_mountpoint | default('/mnt/glusterfs') }}"
      - --host-set
      - "{{ gluster_clients }}"
      - --output-json
      - "{{glusterfs_perf_resdir}}/smallfile/{{item}}"
  delegate_to: "{{ glusterfs_perf_client | default(glusterfs_perf_server) }}"
  run_once: true
  with_items:
     - delete


- name: take profile info output.
  shell: |
      gluster volume profile {{ glusterfs_perf_volume }} info >> {{glusterfs_perf_resdir}}/smallfile/delete-profile
      exit 0
  delegate_to: "{{ glusterfs_perf_server }}"
  run_once: true
  ignore_errors: true
