gluster_nodes:
    hosts:
        benki1-nic2.lab.eng.blr.redhat.com:
        benki2-nic2.lab.eng.blr.redhat.com:
        benki3-nic2.lab.eng.blr.redhat.com:
        benki5-nic2.lab.eng.blr.redhat.com:
        benki6-nic2.lab.eng.blr.redhat.com:
    vars:
        gluster_infra_disktype: RAID6
        gluster_infra_diskcount: 12
        gluster_infra_stripe_unit_size: 128
        gluster_infra_volume_groups:
            - vgname: vg_sdb
              pvname: /dev/sdb
            - vgname: vg_sdc
              pvname: /dev/sdc
        gluster_infra_thinpools:
            - vgname: vg_sdb
              thinpoolname: thinpool_vg_sdb
              thinpoolsize: 45G
              poolmetadatasize: 1G
            - vgname: vg_sdc
              thinpoolname: thinpool_vg_sdc
              thinpoolsize: 45G
              poolmetadatasize: 1G
        gluster_infra_lv_logicalvols:
            - vgname: vg_sdb
              thinpool: thinpool_vg_sdb
              lvname: gluster_lv_disk1
              lvsize: 200G
            - vgname: vg_sdc
              thinpool: thinpool_vg_sdc
              lvname: gluster_lv_disk2
              lvsize: 200G
        gluster_infra_mount_devices:
            - { path: '/disperse1', vgname: vg_sdb, lvname: gluster_lv_disk1 }
            - { path: '/disperse2', vgname: vg_sdc, lvname: gluster_lv_disk2 }

        glusterfs_perf_volume: disperse
        glusterfs_perf_bricks: /disperse1/brick,/disperse2/brick
        glusterfs_perf_disperse_count: 6
        glusterfs_perf_redundancy_count: 2
        glusterfs_perf_force: true

        glusterfs_perf_servers:
            - benki1-nic2.lab.eng.blr.redhat.com
            - benki2-nic2.lab.eng.blr.redhat.com
            - benki3-nic2.lab.eng.blr.redhat.com
        glusterfs_perf_clients:
            - benki5-nic2.lab.eng.blr.redhat.com
            - benki6-nic2.lab.eng.blr.redhat.com
        glusterfs_perf_server: benki1-nic2.lab.eng.blr.redhat.com
        glusterfs_perf_client: benki5-nic2.lab.eng.blr.redhat.com
        glusterfs_perf_hosts: "{{ groups['gluster_nodes'] }}"

        glusterfs_perf_tag: nightly
        glusterfs_perf_resdir_base: "/var/tmp/glusterperf/{{ ansible_date_time.date }}"
        glusterfs_perf_resdir: "{{ glusterfs_perf_resdir_base }}/{{ glusterfs_perf_tag }}/disperse/"
