gluster_nodes:
    hosts:
        benki1-nic2.lab.eng.blr.redhat.com:
        benki2-nic2.lab.eng.blr.redhat.com:
        benki3-nic2.lab.eng.blr.redhat.com:
        benki5-nic2.lab.eng.blr.redhat.com:
        benki6-nic2.lab.eng.blr.redhat.com:

    vars:
        gluster_infra_disktype: RAID6
        gluster_infra_diskcount: 12
        gluster_infra_stripe_unit_size: 128
        gluster_infra_volume_groups:
            - vgname: vg_sdb
              pvname: /dev/sdb
            - vgname: vg_sdc
              pvname: /dev/sdc
            - vgname: vg_sdd
              pvname: /dev/sdd
            - vgname: vg_sde
              pvname: /dev/sde
        gluster_infra_thinpools:
            - vgname: vg_sdb
              thinpoolname: thinpool_vg_sdb
              thinpoolsize: 45G
              poolmetadatasize: 1G
            - vgname: vg_sdc
              thinpoolname: thinpool_vg_sdc
              thinpoolsize: 45G
              poolmetadatasize: 1G
            - vgname: vg_sdd
              thinpoolname: thinpool_vg_sdd
              thinpoolsize: 45G
              poolmetadatasize: 1G
            - vgname: vg_sde
              thinpoolname: thinpool_vg_sde
              thinpoolsize: 45G
              poolmetadatasize: 1G
        gluster_infra_lv_logicalvols:
            - vgname: vg_sdb
              thinpool: thinpool_vg_sdb
              lvname: gluster_lv_disk1
              lvsize: 200G
            - vgname: vg_sdc
              thinpool: thinpool_vg_sdc
              lvname: gluster_lv_disk2
              lvsize: 200G
            - vgname: vg_sdd
              thinpool: thinpool_vg_sdd
              lvname: gluster_lv_disk3
              lvsize: 200G
            - vgname: vg_sde
              thinpool: thinpool_vg_sde
              lvname: gluster_lv_disk4
              lvsize: 200G
        gluster_infra_mount_devices:
            - { path: '/dist1', vgname: vg_sdb, lvname: gluster_lv_disk1 }
            - { path: '/dist2', vgname: vg_sdc, lvname: gluster_lv_disk2 }
            - { path: '/dist3', vgname: vg_sdd, lvname: gluster_lv_disk3 }
            - { path: '/dist4', vgname: vg_sde, lvname: gluster_lv_disk4 }
        glusterfs_perf_volume: distribute-8-bricks
        glusterfs_perf_bricks: /dist1/1,/dist2/1,/dist3/1,/dist4/1

        glusterfs_perf_servers:
            - benki1-nic2.lab.eng.blr.redhat.com
            - benki2-nic2.lab.eng.blr.redhat.com
        glusterfs_perf_clients:
            - benki5-nic2.lab.eng.blr.redhat.com
            - benki6-nic2.lab.eng.blr.redhat.com
        glusterfs_perf_server: benki1-nic2.lab.eng.blr.redhat.com
        glusterfs_perf_client: benki5-nic2.lab.eng.blr.redhat.com
        glusterfs_perf_hosts: "{{ groups['gluster_nodes'] }}"

        glusterfs_perf_tag: nightly
        glusterfs_perf_resdir_base: "/var/tmp/glusterperf/{{ ansible_date_time.date }}"
        glusterfs_perf_resdir: "{{ glusterfs_perf_resdir_base }}/{{ glusterfs_perf_tag }}/distribute/"
        # git_repo
        # git_version
        # git_refspec
