gluster_clients:
    hosts:
        benki5-nic2.lab.eng.blr.redhat.com:
        benki6-nic2.lab.eng.blr.redhat.com:
    vars:
        glusterfs_perf_volume: replicate
        glusterfs_perf_resdir: "{{ glusterfs_perf_resdir_base }}/{{ glusterfs_perf_tag }}/replicate/"

gluster_nodes:
    hosts:
        benki1-nic2.lab.eng.blr.redhat.com:
        benki2-nic2.lab.eng.blr.redhat.com:
        benki3-nic2.lab.eng.blr.redhat.com:
    vars:
        gluster_infra_disktype: RAID6
        gluster_infra_diskcount: 12
        gluster_infra_stripe_unit_size: 128
        gluster_infra_volume_groups:
            - vgname: vg_sdb
              pvname: /dev/sdb
        gluster_infra_thinpools:
            - vgname: vg_sdb
              thinpoolname: thinpool_vg_sdb
              thinpoolsize: 45G
              poolmetadatasize: 1G
        gluster_infra_lv_logicalvols:
            - vgname: vg_sdb
              thinpool: thinpool_vg_sdb
              lvname: gluster_lv_disk1
              lvsize: 200G
        gluster_infra_mount_devices:
            - { path: '/replicate', vgname: vg_sdb, lvname: gluster_lv_disk1 }
        glusterfs_perf_resdir: "{{ glusterfs_perf_resdir_base }}/{{ glusterfs_perf_tag }}/replicate/"
        glusterfs_perf_volume: replicate
        glusterfs_perf_bricks: /replicate/brick
        glusterfs_perf_hosts: "{{ groups['gluster_nodes'] }}"
        glusterfs_perf_replica_count: 3
