---
# tasks file for glusterfs-perf
- name: Pre-requisites for setting up Gluster HCI
  import_tasks: prereq.yml
  tags:
    - prereq

# Setup GlusterFS cluster
- name: Setup GlusterFS cluster
  import_tasks: glustervol.yml
  tags:
    - clustersetup

# Run the performance tool on the cluster
- name: Run smallfile perf tool
  import_tasks: perftests.yml
  tags:
    - runperf