---
# Gather date time data
- name: Gather facts to determine date
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - date_time
  tags:
    - always

# Convert list of clients to comma-separated string
- name: Create a comma-separated list of clients
  set_fact:
        gluster_clients: "{{ glusterfs_perf_clients|join(',') }}"

# tasks file for glusterfs-perf
- name: Pre-requisites for setting up Gluster HCI
  import_tasks: prereq.yml
  tags:
    - prereq

# Setup GlusterFS cluster
- name: Setup GlusterFS cluster
  import_tasks: glustervol.yml
  delegate_to: "{{ glusterfs_perf_server }}"
  tags:
    - clustersetup

# Run the performance tool on the cluster
- name: Run smallfile perf tool
  import_tasks: perftests.yml
  tags:
    - runperf

# Send mail attaching the results
- name: Send mail attaching the results
  import_tasks: sendmail.yml
  tags:
    - mail