---
# Create a directory to store the results
- name: Create a temporary directory to store results
  file:
     state: directory
     path: "{{glusterfs_perf_resdir }}"
  delegate_to: "{{ glusterfs_perf_client | default(glusterfs_perf_server) }}"
  run_once: true

# Import the tests
- import_tasks: createdelete.yml
  tags: createdelete

- import_tasks: appendoverwrite.yml
  tags: appendoverwrite

- import_tasks: read.yml
  tags: read

- import_tasks: readdir.yml
  tags: readdir

- import_tasks: rename.yml
  tags: rename

- import_tasks: symlink.yml
  tags: symlink

- import_tasks: mkdir.yml
  tags: mkdir

- import_tasks: stat.yml
  tags: stat

- import_tasks: chmod.yml
  tags: chmod

- import_tasks: setxattr.yml
  tags: setxattr

- import_tasks: ls-l.yml
  tags: ls
