---
- name: Clean up GlusterFS mountpoint
  file:
     state: absent
     path: "{{glusterfs_perf_mountpoint|default('/mnt/glusterfs')}}/{{item}}"
  with_items:
     - file_dstdir
     - file_srcdir
     - network_shared
  delegate_to: "{{ glusterfs_perf_client | default(glusterfs_perf_server) }}"
  run_once: true


# Create a directory to store the results
- name: Create a temporary directory to store results
  file:
     state: directory
     path: "{{ glusterfs_perf_resdir | default('/var/tmp/glusterperf') }}"
  delegate_to: "{{ glusterfs_perf_client | default(glusterfs_perf_server) }}"
  run_once: true

# Run the perf tool on the mountpoint
- name: Run smallfile tests
  command:
  args:
    argv:
      - /usr/src/smallfile/smallfile_cli.py
      - --stonewall
      - N
      - --operation
      - "{{ item }}"
      - --threads
      - 8
      - --file-size
      - 64
      - --files
      - 2500
      - --top
      - "{{ glusterfs_perf_mountpoint | default('/mnt/glusterfs') }}"
      - --host-set
      - "{{ glusterfs_perf_client | default(glusterfs_perf_server) }}"
      - --output-json
      - "{{ glusterfs_perf_resdir|default('/var/tmp/glusterperf') }}/{{item}}-{{ansible_date_time.date}}"
  delegate_to: "{{ glusterfs_perf_client | default(glusterfs_perf_server) }}"
  run_once: true
  with_items:
     - create
     - append
     - mkdir
     - chmod
     - rename
     - rmdir