---
# Install the packages needed to fetch GlusterFS project and build
# We need the epel release for userspace rcu.
- name: Initialise the packages that have to be installed
  set_fact:
     packages:
       - autoconf
       - automake
       - bison
       - e2fsprogs-devel
       - firewalld
       - flex
       - fuse-devel
       - gcc
       - git
       - libacl-devel
       - libaio-devel
       - libattr-devel
       - libcmocka-devel
       - libibverbs-devel
       - librdmacm-devel
       - libtirpc-devel
       - libtool
       - libuuid-devel
       - libxml2-devel
       - lvm2-devel
       - make
       - ncurses-devel
       - openssl-devel
       - python-ctypes
       - python-devel
       - python-simplejson
       - python-matplotlib
       - rdma-core-devel
       - readline-devel
       - sqlite-devel
       - systemd
       - userspace-rcu-devel

- name: Add EPEL repository (we need it for a few extra packages)
  yum:
    name: 'http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
    state: present

- name: Install the necessary packages
  yum:
    name: "{{ packages }}"
    state: present

- name: Clone glusterfs git repository
  git:
    clone: yes
    depth: 1
    update: yes
    dest: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"
    repo: "{{ glusterfs_perf_git_repo | default('https://github.com/gluster/glusterfs.git') }}"
    version: "{{ glusterfs_perf_git_version | default('master') }}"
    refspec: "{{ glusterfs_perf_git_refspec | default(omit) }}"

- name: Clone smallfile perf git repository
  git:
    clone: yes
    depth: 1
    update: yes
    dest: "{{ smallfile_perf_git_dest | default('/usr/src/smallfile') }}"
    repo: https://github.com/distributed-system-analysis/smallfile.git

- name: Clone the glusterfs.perf role
  git:
    clone: yes
    update: yes
    dest: /etc/ansible/roles/glusterfs.perf
    repo: https://github.com/gluster/glusterfs-perf.git
  ignore_errors: true
  delegate_to: "{{ item }}"
  with_items: "{{ glusterfs_perf_clients }}"
  run_once: true

# Run autogen and configure to generate makefile
- name: Generate configure file
  command: ./autogen.sh
  args:
    chdir: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"

# The test expects the version to be a string of type vX.string where X is
# an integer
- name: Configure without-libtirpc if version is set
  set_fact:
     wolibtirpc: "--without-libtirpc"
  when: glusterfs_perf_git_version is not defined or
        glusterfs_perf_git_version[1]|int < 6

- name: Run configure to generate Makefile for building GlusterFS
  command: ./configure "{{ wolibtirpc | default('') }}"
  args:
    chdir: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"

- name: Build and install GlusterFS
  make:
    chdir: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"
    target: install

# Can't do make install in a single command witht his module
- name: Clean build directory
  make:
    chdir: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"
    target: distclean
