---
# Install the packages needed to fetch GlusterFS project and build
# We need the epel release for userspace rcu.
- name: Initialise the packages that have to be installed
  set_fact:
     packages:
       - autoconf
       - automake
       - bison
       - e2fsprogs-devel
       - firewalld
       - flex
       - fuse-devel
       - gcc
       - git
       - libacl-devel
       - libaio-devel
       - libattr-devel
       - libcmocka-devel
       - libibverbs-devel
       - librdmacm-devel
       - libtirpc-devel
       - libtool
       - libuuid-devel
       - libxml2-devel
       - lvm2-devel
       - make
       - ncurses-devel
       - openssl-devel
       - python-ctypes
       - python-devel
       - python-simplejson
       - python-matplotlib
       - rdma-core-devel
       - readline-devel
       - sqlite-devel
       - systemd
       - userspace-rcu-devel
       - zlib-devel
       - libaio
       - fio
       - postgresql11
       - postgresql11-contrib
       - postgresql11-server

- name: Add EPEL repository (we need it for a few extra packages)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    - https://download.postgresql.org/pub/repos/yum/11/redhat/rhel-7-x86_64/pgdg-centos11-11-2.noarch.rpm

- name: Install the necessary packages
  yum:
    name: "{{ packages }}"
    state: present

- name: Install pip
  command: "{{ item }}"
  with_items:
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python get-pip.py
    - pip install pexpect

# If there are local changes, git checkout etc doesn't work.
# The directory may not exist in first run, which is not an error
- name: Clean glusterfs source directory
  shell: |
      git clean -f
      git stash
  ignore_errors: true
  args:
    chdir: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"

- name: Git checkout glusterfs
  git:
    depth: 1
    clone: yes
    update: yes
    repo: "{{ glusterfs_perf_git_repo | default('https://github.com/gluster/glusterfs.git') }}"
    dest: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"
    version: "{{ glusterfs_perf_git_version | default('master') }}"
  when: glusterfs_perf_git_refspec is not defined

- name: Git Checkout glusterfs (refspec)
  shell: |
      git fetch {{ glusterfs_perf_git_repo }} {{ glusterfs_perf_git_refspec }} &&
      git checkout -b test-{{ ansible_date_time.epoch }} FETCH_HEAD
  args:
    chdir: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"
  when: glusterfs_perf_git_refspec is defined

- name: Clone smallfile perf git repository
  git:
    clone: yes
    depth: 1
    update: yes
    dest: "{{ smallfile_perf_git_dest | default('/usr/src/smallfile') }}"
    repo: https://github.com/distributed-system-analysis/smallfile.git

- name: Clone the glusterfs.perf role
  git:
    clone: yes
    update: yes
    dest: /etc/ansible/roles/glusterfs.perf
    repo: https://github.com/gluster/glusterfs-perf.git
  ignore_errors: true
  delegate_to: "{{ item }}"
  with_items: "{{ glusterfs_perf_clients }}"
  when: glusterfs_perf_clients is defined
  run_once: true

# Run autogen and configure to generate makefile
- name: Generate configure file
  command: ./autogen.sh
  args:
    chdir: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"

# The test expects the version to be a string of type vX.string where X is
# an integer
- name: Configure without-libtirpc if version is set
  set_fact:
     wolibtirpc: "--without-libtirpc"
  when: glusterfs_perf_git_version is not defined or
        glusterfs_perf_git_version[1]|int < 6

- name: Run configure to generate Makefile for building GlusterFS
  command: ./configure "{{ wolibtirpc | default('') }}"
  args:
    chdir: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"

# There can be some generated .c files, which gives an warning of 'overwriting'
# if make clean is not done before
- name: Clean glusterfs source directory
  make:
    chdir: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"
    target: clean

# Can't do make install in a single command with this module
- name: Build and install GlusterFS
  make:
    chdir: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"
    target: install

# Can't do make install in a single command with this module
- name: Clean build directory
  make:
    chdir: "{{ glusterfs_perf_git_dest | default('/usr/src/glusterfs') }}"
    target: distclean
