---

# Point to the git repo you want to clone from (and also the version/tag)
#
# glusterfs_perf_git_repo: https://review.gluster.org/glusterfs
# glusterfs_perf_git_version: release-6

# check which refspec you need to fetch. If you want to test particular
# patch, you would need to set it up. Remember to uncomment above variable
# too, if you want to use this. (Visible when you press 'Download'
# in https://review.gluster.org, particular patch.
#
# glusterfs_perf_git_refspec: refs/changes/36/20636/21
# git_repo
# git_refspec
# git_version

glusterfs_perf_tag: nightly
