gluster_clients:
    hosts:
        benki5-nic2.lab.eng.blr.redhat.com:
        benki6-nic2.lab.eng.blr.redhat.com:

gluster_nodes:
    hosts:
        benki1-nic2.lab.eng.blr.redhat.com:
        benki2-nic2.lab.eng.blr.redhat.com:
        benki3-nic2.lab.eng.blr.redhat.com:
