# Send mail attaching the results
- name: Send mail attaching the results
  remote_user: root
  gather_facts: true
  hosts: all
  tasks:
    - name: include common variables
      include_vars: common-vars.yml

    - name: Send mail attaching the results
      import_tasks: sendmail.yml
      when: glusterfs_perf_to_list is defined
      tags:
        - mail
